.\"                                      Hey, EMACS: -*- nroff -*-
.\" © Copyright 2023 Sven Buschke <sven©buschke.com>
.\"
.TH SVENUTILS 1
.SH NAME
svenutils \- utilies by Sven Buschke
.SH SYNOPSIS
.B several, see single programs
.SH DESCRIPTION
The
.B svenutils
suite covers several programs:
- createProject
.SH SEE ALSO
cleanProjectFolder
continueProjects
createProject
createProjectWSL
mountWSL
update
.BR cleanProjectFolder (1).
.SH AUTHORS
The
.B svenutils
suite was written by
Sven Buschke <sven@buschke.com>
.PP
This document was written by Sven Buschke <sven@buschke.com>, © January, 2023 22 - January 7, 2023, Sven Buschke.%