.\"                                      Hey, EMACS: -*- nroff -*-
.\" © Copyright 2022 Sven Buschke <sven©buschke.com>
.\"
.TH SVEN UTILS
.SH NAME
test \- test application
.SH SYNOPSIS
.B test.sh
.SH DESCRIPTION
The
.B test
prints the name.
.SH SEE ALSO
.BR echo (1).
.SH AUTHORS
The
.B test
script was written by
Sven Buschke <sven@buschke.com>
.PP
This document was written by Sven Buschke <sven@buschke.com>.