.\" update, Part of svenutils
.TH UPDATE 1
.SH NAME
update \- script for updating the system
.SH SYNOPSIS
.B update
.SH DESCRIPTION
This script updates the system through the following subscripts:
.PP
apt
.PP
pip
.PP
nvm
.SH SEE ALSO
None
.SH AUTHORS
Sven Buschke
.SH COPYRIGHT
© January 7, 2023, Sven Buschke